# Generated by Django 4.2.5 on 2023-10-11 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_car_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='car_image',
        ),
    ]
